management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
    # 可以省略
    schema: 'classpath:schema.sql'
    data: 'classpath:data.sql'