spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    schema: schema.sql
    data: data.sql
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5