management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  output:
    ansi:
      enabled: ALWAYS

foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password:
    schema: 'foo.sql'

bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: sa
    password:
    schema: 'bar.sql'