spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password: ItzTOJZ9BAaaUYWTIXvVcxgLeFFOpMzYKajgHD/8DTvvXOOolOt8DhlLY6w6+qEJOeT20/RUlFz7eTnH/pDtJQ==
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: config,stat,slf4j,wall,myfilter
      filter:
        config:
          enabled: true
        wall: # sql 防注入等配置
          enabled: true
          db-type: h2
          config:
            drop-table-allow: false
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      connection-properties: 'config.decrypt=true;config.decrypt.key=${public-key}'
      stat-view-servlet: #页面监控
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin


public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnZDAfPXKfGC64wm1IfOiqe/zTfGxsPZE38t51aRXH6boNczOSEcKoxwQvE6CjBydEFS67CV3s7VOI1iOszyX8CAwEAAQ==
